// tarot-day.js — тексты для «Карты дня» (прямое/перевёрнутое, ru/en).
// Ключи — id карт из tarot-data.js (maj0..21, wands1..14, cups1..14, swords1..14, pentacles1..14).
window.TAROT_DAY_TEXT = {
  maj0: {
    ru: "День когда стоит довериться себе и просто сделать. Не думай слишком долго — сегодня интуиция важнее логики. Если давно откладываешь какое-то решение, сегодня хороший день чтобы наконец шагнуть.",
    ruRev: "Сегодня легко наломать дров действуя импульсивно. Прежде чем делать — остановись на минуту и подумай. Энергия есть, но она сейчас немного вразнос. Притормози.",
    en: "Today is a good day to just go for it. Stop overthinking and trust your gut — it knows more than your head right now. If you've been putting something off, today's the day to finally take that step.",
    enRev: "Easy to act on impulse today and regret it later. Before you do anything — pause for a second. The energy is there but it's a bit scattered. Slow down.",
  },
  maj1: {
    ru: "У тебя сегодня есть всё что нужно — просто посмотри внимательнее. Не жди идеальных условий, ресурсы уже есть. Хороший день чтобы начать, запустить, договориться.",
    ruRev: "Что-то идёт не так и ты это чувствуешь. Возможно, берёшься за слишком многое сразу или пытаешься казаться увереннее чем есть. Сфокусируйся на одном деле.",
    en: "You already have everything you need today — look closer. Don't wait for perfect conditions, the resources are already there. Good day to start something, launch, or make a deal.",
    enRev: "Something feels off and you know it. You might be taking on too much at once or pretending to be more confident than you feel. Pick one thing and focus.",
  },
  maj2: {
    ru: "Сегодня не день для громких действий. Понаблюдай, послушай, побудь в тишине. Ответ который ты ищешь уже есть внутри — просто дай себе время его услышать.",
    ruRev: "Ты игнорируешь что-то важное — скорее всего своё же ощущение что что-то не так. Перестань заглушать внутренний голос и наконец прислушайся к нему.",
    en: "Today is not the day for big moves. Observe, listen, sit with the silence. The answer you're looking for is already inside you — just give yourself time to hear it.",
    enRev: "You're ignoring something important — probably your own gut feeling that something's off. Stop drowning out that inner voice and actually listen to it.",
  },
  maj3: {
    ru: "Хороший день чтобы побаловать себя, замедлиться и получить удовольствие от простых вещей. Позволь себе отдохнуть без чувства вины — это тоже продуктивность.",
    ruRev: "Ты выжата или игнорируешь свои базовые потребности. Когда ты последний раз нормально поела, поспала, подышала? Начни с этого.",
    en: "Good day to treat yourself, slow down and enjoy simple things. Let yourself rest without guilt — that's productive too.",
    enRev: "You're running on empty or ignoring your basic needs. When did you last eat properly, sleep well, breathe? Start there.",
  },
  maj4: {
    ru: "День для структуры и конкретных действий. Составь план, расставь приоритеты, возьми ситуацию под контроль. Сегодня хаос не твой друг — чёткость и порядок дадут результат.",
    ruRev: "Ты либо пытаешься контролировать то что не в твоей власти, либо наоборот — избегаешь ответственности. Найди баланс между жёсткостью и гибкостью.",
    en: "Day for structure and concrete action. Make a plan, set priorities, take control of the situation. Chaos is not your friend today — clarity and order will get results.",
    enRev: "You're either trying to control things that aren't yours to control, or avoiding responsibility altogether. Find the balance between rigid and flexible.",
  },
  maj5: {
    ru: "Сегодня стоит обратиться к тому кто знает больше — спросить совета, поучиться, послушать опыт других. Иногда не надо изобретать велосипед.",
    ruRev: "Тебе навязывают чужие правила или ты сам себя загнал в рамки которые уже не работают. Спроси себя — это действительно твои убеждения или чужие?",
    en: "Today it's worth turning to someone who knows more — ask for advice, learn something, listen to others' experience. Sometimes you don't have to reinvent the wheel.",
    enRev: "Someone is pushing their rules on you, or you've boxed yourself into frameworks that no longer work. Ask yourself — are these actually your beliefs, or someone else's?",
  },
  maj6: {
    ru: "День выбора — и скорее всего ты уже знаешь какой. Не тот который правильный по чьим-то меркам, а тот который честный для тебя. Доверяй этому.",
    ruRev: "Есть конфликт — внутри себя или с кем-то близким. Избегать его не получится, лучше разобраться сейчас пока не затянулось.",
    en: "Day of choice — and you probably already know which one. Not the one that looks right by someone else's standards, but the one that's honest for you. Trust that.",
    enRev: "There's a conflict — inside yourself or with someone close. Avoiding it won't work, better to deal with it now before it drags on.",
  },
  maj7: {
    ru: "Сегодня можно многое — если не распыляться. Сфокусируйся на одной цели и двигайся к ней без остановок. Энергия и воля есть, главное направить их в одну точку.",
    ruRev: "Тянешь в разные стороны одновременно — и никуда не едешь. Определи наконец что для тебя важнее прямо сейчас и останови внутренний раздрай.",
    en: "You can accomplish a lot today — if you don't scatter your energy. Focus on one goal and move toward it without stopping. The drive is there, just point it in one direction.",
    enRev: "You're pulling in different directions at once — and going nowhere. Decide what actually matters most right now and stop the internal tug-of-war.",
  },
  maj8: {
    ru: "Сегодня понадобится терпение а не напор. Мягко но уверенно — так сейчас работает лучше чем в лоб. Ты справишься с тем что кажется сложным, просто не торопи.",
    ruRev: "Ты либо слишком давишь — на себя или других, либо наоборот слишком мягко стелешь там где нужна твёрдость. Найди свою точку уверенности без агрессии.",
    en: "Today calls for patience, not force. Gentle but steady — that works better right now than going head-on. You'll handle what seems hard, just don't rush it.",
    enRev: "You're either pushing too hard — yourself or others — or being too soft where you need to be firm. Find your point of confidence without aggression.",
  },
  maj9: {
    ru: "Побудь сегодня наедине с собой — это не одиночество, это необходимость. Шум и суета мешают услышать то важное что давно пытается до тебя достучаться.",
    ruRev: "Ты либо слишком закрылся от людей, либо наоборот — бежишь от себя в толпу. В обоих случаях чего-то избегаешь. Стоит разобраться чего именно.",
    en: "Spend some time alone today — it's not loneliness, it's a necessity. The noise and busyness are blocking something important that's been trying to reach you.",
    enRev: "You're either too closed off from people, or running from yourself into the crowd. Either way you're avoiding something. Worth figuring out what.",
  },
  maj10: {
    ru: "Что-то меняется — и это не в твоей власти остановить. Прими это как данность и подумай как использовать перемену в свою пользу, а не как с ней бороться.",
    ruRev: "Ощущение что всё идёт не так и удача отвернулась. Но честно — что ты сам сделал чтобы изменить ситуацию? Колесо крутится в обе стороны.",
    en: "Something is shifting — and it's not yours to stop. Accept it and think about how to use this change to your advantage rather than fighting it.",
    enRev: "Feels like everything's going wrong and luck has turned away. But honestly — what have you actually done to change the situation? The wheel spins both ways.",
  },
  maj11: {
    ru: "День для честных решений. Не тех что удобны, а тех что правильны. Если что-то давно требует справедливого разбора — сегодня хороший момент.",
    ruRev: "Ты либо избегаешь последствий своих действий, либо несправедливо судишь — себя или других. Посмотри на ситуацию трезво, без оправданий.",
    en: "Day for honest decisions. Not the convenient ones, but the right ones. If something has needed a fair reckoning for a while — today's a good moment.",
    enRev: "You're either avoiding the consequences of your actions, or judging unfairly — yourself or others. Look at the situation clearly, without excuses.",
  },
  maj12: {
    ru: "Сегодня не надо ничего делать — надо думать. Пауза это не потеря времени, это смена угла зрения. Посмотри на ситуацию иначе и решение может оказаться неожиданным.",
    ruRev: "Ты завис и сам это знаешь. Либо боишься принять решение, либо тянешь время в надежде что всё само разрешится. Не разрешится. Пора двигаться.",
    en: "Today you don't need to do anything — you need to think. A pause isn't wasted time, it's a shift in perspective. Look at the situation differently and the answer might surprise you.",
    enRev: "You're stuck and you know it. Either afraid to make a decision, or stalling hoping things resolve themselves. They won't. Time to move.",
  },
  maj13: {
    ru: "Что-то заканчивается — и это нормально. Не держись за то что уже отжило своё. Освободи место и увидишь что за этим концом стоит начало чего-то лучшего.",
    ruRev: "Ты цепляешься за то что давно пора отпустить. Отношения, работу, убеждения, привычки. Страх перемен понятен, но он дороже обходится чем сами перемены.",
    en: "Something is ending — and that's okay. Don't hold onto what has already run its course. Clear the space and you'll see that behind this ending is the start of something better.",
    enRev: "You're clinging to something you should have let go of a long time ago. A relationship, job, belief, habit. Fear of change is understandable, but it costs more than the change itself.",
  },
  maj14: {
    ru: "День для баланса и терпения. Не надо торопить события или перегибать палку в ту или иную сторону. Двигайся ровно, без крайностей — сегодня это работает лучше всего.",
    ruRev: "Ты сейчас в крайности — либо слишком много, либо слишком мало. Всё или ничего не работает в долгую. Найди середину.",
    en: "Day for balance and patience. No need to rush things or go to extremes in either direction. Move steadily, without extremes — that works best today.",
    enRev: "You're in an extreme right now — either too much or too little. All-or-nothing doesn't work long term. Find the middle ground.",
  },
  maj15: {
    ru: "Что-то тебя держит — и стоит честно разобраться что именно. Привычка, страх, зависимость, токсичная ситуация. Цепи которые ты видишь на карте — часто те что мы сами на себя надели.",
    ruRev: "Ты начинаешь выбираться из чего-то что тебя держало. Это требует усилий, но ты уже двигаешься в правильную сторону. Не возвращайся.",
    en: "Something is holding you — and it's worth being honest about what. A habit, fear, dependency, toxic situation. The chains you see in this card are often the ones we put on ourselves.",
    enRev: "You're starting to break free from something that had a hold on you. It takes effort, but you're already moving in the right direction. Don't go back.",
  },
  maj16: {
    ru: "День может принести неожиданный поворот — что-то рухнет или резко изменится. Это неприятно, но часто именно так жизнь убирает то что мешало двигаться вперёд.",
    ruRev: "Ты избегаешь неизбежного — откладываешь разговор, решение, перемены. Чем дольше тянешь, тем громче будет когда всё-таки рванёт.",
    en: "The day might bring an unexpected turn — something could collapse or shift suddenly. It's uncomfortable, but often this is how life clears away what was blocking your path.",
    enRev: "You're avoiding the inevitable — putting off a conversation, decision, change. The longer you wait, the louder it'll be when it finally goes.",
  },
  maj17: {
    ru: "Хороший день. Просто хороший. Позволь себе немного надежды и доверия к тому что всё идёт как надо. Иногда не нужно ничего форсировать — достаточно просто быть.",
    ruRev: "Ты разочарован или потерял веру в то что что-то изменится. Это понятно. Но уныние сейчас — плохой советчик. Попробуй найти хоть одну маленькую вещь которая даёт надежду.",
    en: "Good day. Just a good day. Allow yourself a little hope and trust that things are going as they should. Sometimes you don't need to force anything — just being is enough.",
    enRev: "You're disappointed or lost faith that anything will change. That's understandable. But despair is a bad advisor right now. Try to find even one small thing that gives you hope.",
  },
  maj18: {
    ru: "Сегодня всё немного туманно — и это нормально. Не принимай важных решений если чувствуешь что картина неполная. Дай ситуации проясниться, не гони.",
    ruRev: "Туман начинает рассеиваться. То что казалось непонятным или пугающим — постепенно проясняется. Доверяй тому что видишь сейчас, не тому что придумал в тревоге.",
    en: "Things feel a bit foggy today — and that's okay. Don't make important decisions if you feel like you're missing the full picture. Let the situation clear up, don't rush.",
    enRev: "The fog is starting to lift. What seemed confusing or scary is gradually becoming clearer. Trust what you can actually see now, not what anxiety made up.",
  },
  maj19: {
    ru: "Один из лучших дней в колоде. Энергия есть, настроение хорошее или будет хорошим. Позволь себе порадоваться, не ищи подвох там где его нет.",
    ruRev: "Что-то мешает тебе почувствовать радость — возможно ты слишком в голове или ждёшь подвоха. Попробуй просто выйти на воздух и переключиться.",
    en: "One of the best cards in the deck. Energy is up, mood is good or will be. Let yourself enjoy it — don't look for a catch where there isn't one.",
    enRev: "Something is blocking you from feeling joy — maybe you're too in your head or waiting for things to go wrong. Try just stepping outside and switching gears.",
  },
  maj20: {
    ru: "День переосмысления. Что-то в твоей жизни требует честной оценки — без самобичевания, но и без самооправданий. Посмотри на ситуацию как есть и реши что дальше.",
    ruRev: "Ты застрял в прошлом — либо в сожалениях, либо в обидах. Это мешает двигаться. Пора наконец закрыть эту страницу и начать новую.",
    en: "Day of reassessment. Something in your life needs an honest evaluation — without self-flagellation, but without self-justification either. See it as it is and decide what's next.",
    enRev: "You're stuck in the past — either in regrets or resentments. It's holding you back. Time to finally close that chapter and start a new one.",
  },
  maj21: {
    ru: "Что-то завершается — и это завершение хорошее. Ты дошёл до конца какого-то этапа. Позволь себе это признать и почувствовать удовлетворение прежде чем бежать к следующему.",
    ruRev: "Ты почти у цели но что-то мешает дойти до конца. Посмотри что именно — возможно дело в страхе успеха или нежелании признать что этот этап закончился.",
    en: "Something is completing — and it's a good completion. You've reached the end of a cycle. Let yourself acknowledge that and feel the satisfaction before rushing to the next thing.",
    enRev: "You're almost at the finish line but something is stopping you from getting there. Look at what — it might be fear of success or reluctance to admit this chapter is over.",
  },
  wands1: {
    ru: "Сегодня появляется новая идея или импульс — не откладывай, хватай пока горит. Это начало чего-то интересного, даже если пока не ясно чего именно.",
    ruRev: "Есть желание но нет энергии на старт. Или наоборот — куча планов но ни один не запускается. Начни с самого маленького шага, остальное подтянется.",
    en: "A new idea or impulse shows up today — don't delay, grab it while it's hot. This is the start of something interesting, even if it's not clear what yet.",
    enRev: "There's desire but no energy to start. Or the opposite — lots of plans but none are launching. Start with the smallest possible step, the rest will follow.",
  },
  wands2: {
    ru: "Ты стоишь на пороге и смотришь вперёд. Планы есть, видение есть — теперь нужно выбрать направление и начать двигаться, а не просто мечтать.",
    ruRev: "Страх неизвестности мешает сделать шаг. Ты планируешь и перепланируешь, но так и не стартуешь. В какой-то момент надо просто начать.",
    en: "You're standing at the threshold looking forward. You have plans, you have vision — now you need to pick a direction and start moving, not just dreaming.",
    enRev: "Fear of the unknown is stopping you from taking the step. You plan and replan but never actually start. At some point you just have to begin.",
  },
  wands3: {
    ru: "То что ты запустил раньше начинает давать результаты. Хороший день чтобы расширить горизонты — подумать о следующем шаге, большем масштабе.",
    ruRev: "Что-то задерживается или идёт не по плану. Не паникуй — проверь детали, возможно нужна небольшая корректировка курса.",
    en: "What you set in motion earlier is starting to show results. Good day to expand your horizons — think about the next step, a bigger scale.",
    enRev: "Something is delayed or not going to plan. Don't panic — check the details, maybe a small course correction is needed.",
  },
  wands4: {
    ru: "День для радости и праздника — пусть небольшого. Отметь то что уже сделано, побудь с людьми которые тебя поддерживают. Ты заслуживаешь немного отдыха.",
    ruRev: "Что-то мешает расслабиться и порадоваться. Может в отношениях напряжение, может внутреннее беспокойство. Попробуй разобраться что мешает просто выдохнуть.",
    en: "Day for joy and celebration — even a small one. Acknowledge what you've already done, spend time with people who support you. You deserve a little rest.",
    enRev: "Something is stopping you from relaxing and enjoying yourself. Maybe tension in relationships, maybe internal worry. Try to figure out what's getting in the way of just breathing.",
  },
  wands5: {
    ru: "Вокруг много суеты и возможно споров. Не вступай в каждую перепалку — выбери свои битвы. Не всё что раздражает, достойно твоей энергии.",
    ruRev: "Конфликт который тянулся начинает стихать. Или ты наконец перестаёшь бороться с ветряными мельницами. В любом случае — это хорошо.",
    en: "Lots of hustle and possibly arguments around you. Don't engage in every dispute — pick your battles. Not everything that irritates you deserves your energy.",
    enRev: "A conflict that's been dragging on is starting to settle. Or you're finally stopping the fight against windmills. Either way — that's good.",
  },
  wands6: {
    ru: "День признания и маленькой победы. Что-то идёт хорошо — позволь себе это заметить. Можно немного погордиться собой, это не зазнайство.",
    ruRev: "Ждёшь признания которое не приходит или сомневаешься в себе несмотря на результаты. Напомни себе что внешнее одобрение — приятно, но не обязательно.",
    en: "Day of recognition and a small victory. Something is going well — let yourself notice it. It's okay to be a little proud of yourself, that's not arrogance.",
    enRev: "Waiting for recognition that isn't coming, or doubting yourself despite the results. Remind yourself that external approval is nice — but not required.",
  },
  wands7: {
    ru: "Придётся отстаивать свою позицию. Это не повод для агрессии, но и уступать там где ты прав — не нужно. Держи свою точку зрения спокойно и уверенно.",
    ruRev: "Ты либо сдаёшься там где надо стоять, либо защищаешься там где угрозы нет. Разбери что именно происходит прежде чем реагировать.",
    en: "You'll need to defend your position. That's not a reason for aggression, but you don't need to give in where you're right either. Hold your ground calmly and confidently.",
    enRev: "You're either giving up where you should stand firm, or defending yourself where there's no real threat. Figure out what's actually happening before you react.",
  },
  wands8: {
    ru: "Всё начинает двигаться быстро. Новости, решения, события — сегодня может многое сдвинуться с места. Будь готов действовать оперативно.",
    ruRev: "Всё идёт медленнее чем хочется или есть задержки. Не пытайся форсировать — иногда задержка это защита от ошибки.",
    en: "Things are starting to move fast. News, decisions, events — a lot might shift today. Be ready to act quickly.",
    enRev: "Things are moving slower than you'd like or there are delays. Don't try to force it — sometimes a delay is protection from a mistake.",
  },
  wands9: {
    ru: "Ты устал, но почти у цели. Не сдавайся сейчас — именно последний рывок часто самый важный. У тебя есть силы, даже если кажется что нет.",
    ruRev: "Ты вымотан и упрямо продолжаешь там где стоит остановиться и отдохнуть. Передышка — это не слабость. Иногда пауза лучше чем ещё один рывок на износ.",
    en: "You're tired but almost at the finish. Don't give up now — the last push is often the most important one. You have the strength, even if it doesn't feel like it.",
    enRev: "You're exhausted and stubbornly pushing on when you should stop and rest. Taking a break is not weakness. Sometimes a pause beats another push to the limit.",
  },
  wands10: {
    ru: "Ты несёшь слишком много. Посмотри на свой список дел и спроси — а всё ли из этого действительно твоё? Что-то можно делегировать или вообще убрать.",
    ruRev: "Ты начинаешь сбрасывать лишний груз — и правильно делаешь. Научиться говорить нет это не эгоизм, это необходимость.",
    en: "You're carrying too much. Look at your to-do list and ask — is all of this actually yours to carry? Something can be delegated or dropped entirely.",
    enRev: "You're starting to shed the extra load — and that's the right move. Learning to say no isn't selfish, it's necessary.",
  },
  wands11: {
    ru: "День для новых идей и любопытства. Попробуй что-то что давно хотел но откладывал. Сегодня не нужно быть экспертом — достаточно просто начать.",
    ruRev: "Много идей, мало действий. Или начал и бросил на полпути. Выбери одно и доведи хотя бы до промежуточного результата.",
    en: "Day for new ideas and curiosity. Try something you've wanted to do but kept putting off. Today you don't need to be an expert — just starting is enough.",
    enRev: "Lots of ideas, little action. Or started something and dropped it halfway. Pick one thing and see it through to at least an intermediate result.",
  },
  wands12: {
    ru: "Энергии много — используй её. День для смелых действий и движения вперёд. Только не забудь хотя бы немного подумать перед тем как прыгать.",
    ruRev: "Импульсивность сегодня может дорого обойтись. Ты мчишься вперёд не глядя — притормози и убедись что знаешь куда едешь.",
    en: "There's a lot of energy — use it. Day for bold action and moving forward. Just remember to think at least a little before you leap.",
    enRev: "Impulsiveness can cost you today. You're charging forward without looking — slow down and make sure you know where you're going.",
  },
  wands13: {
    ru: "День уверенности и харизмы. Ты можешь сегодня зажечь других — своей энергией, идеями, присутствием. Не стесняйся занимать пространство.",
    ruRev: "Что-то гасит твой огонь — усталость, чужая критика, сомнения. Напомни себе кто ты есть когда на высоте. Это всё ещё ты.",
    en: "Day of confidence and charisma. You can inspire others today — with your energy, ideas, presence. Don't be shy about taking up space.",
    enRev: "Something is dampening your fire — exhaustion, criticism, self-doubt. Remind yourself who you are when you're at your best. That's still you.",
  },
  wands14: {
    ru: "День для лидерства и стратегии. Если нужно принять решение или взять инициативу — сейчас твой момент. Действуй с позиции силы, не реакции.",
    ruRev: "Ты либо давишь на других своей силой, либо наоборот — не берёшь ответственность когда нужно. Найди баланс между контролем и доверием.",
    en: "Day for leadership and strategy. If a decision needs to be made or initiative needs to be taken — this is your moment. Act from a position of strength, not reaction.",
    enRev: "You're either pushing too hard on others, or avoiding responsibility when it's needed. Find the balance between control and trust.",
  },
  cups1: {
    ru: "День открытого сердца. Позволь себе почувствовать — радость, нежность, связь с другими. Хороший день для всего что связано с эмоциями и близостью.",
    ruRev: "Что-то мешает тебе открыться — старые обиды, страх уязвимости. Это понятно. Но закрытое сердце не защищает, оно просто одиноко.",
    en: "Day of an open heart. Let yourself feel — joy, tenderness, connection with others. Good day for everything related to emotions and closeness.",
    enRev: "Something is stopping you from opening up — old wounds, fear of vulnerability. That's understandable. But a closed heart doesn't protect you, it just keeps you lonely.",
  },
  cups2: {
    ru: "День для связи с другим человеком. Встреча, разговор, сближение — что-то в отношениях может выйти на новый уровень. Будь открыт.",
    ruRev: "В каких-то отношениях есть напряжение или дисбаланс. Стоит поговорить честно, пока недопонимание не выросло в стену.",
    en: "Day for connection with another person. A meeting, conversation, coming closer — something in a relationship might reach a new level. Be open.",
    enRev: "There's tension or imbalance in some relationship. Worth having an honest conversation before the misunderstanding grows into a wall.",
  },
  cups3: {
    ru: "День для радости с близкими. Встреться с друзьями, отпразднуй что-то вместе, просто побудь в хорошей компании. Связи с людьми сегодня важнее дел.",
    ruRev: "Что-то нарушает гармонию в кругу близких — сплетни, зависть, недопонимание. Не вовлекайся в чужие игры.",
    en: "Day for joy with close ones. Meet friends, celebrate something together, just spend time in good company. Connections with people matter more than tasks today.",
    enRev: "Something is disrupting harmony in your close circle — gossip, jealousy, misunderstanding. Don't get drawn into other people's games.",
  },
  cups4: {
    ru: "Ты немного в апатии или всё кажется пресным. Это нормально — иногда нужна пауза. Но посмотри внимательнее — рядом может быть возможность которую ты не замечаешь.",
    ruRev: "Апатия начинает отступать. Ты снова готов замечать жизнь вокруг. Хороший момент чтобы выйти из режима наблюдателя.",
    en: "You're feeling a bit apathetic or everything seems bland. That's normal — sometimes you need a pause. But look closer — there might be an opportunity nearby that you're missing.",
    enRev: "The apathy is starting to lift. You're ready to notice life around you again. Good moment to step out of observer mode.",
  },
  cups5: {
    ru: "Ты переживаешь потерю или разочарование. Это больно и это нормально — не надо торопиться выходить из этого чувства. Но не забудь: за спиной ещё стоят два полных кубка.",
    ruRev: "Ты начинаешь выходить из горя или разочарования. Медленно, но двигаешься. Это уже немало.",
    en: "You're going through a loss or disappointment. It hurts and that's okay — you don't need to rush out of this feeling. But don't forget: there are still two full cups behind you.",
    enRev: "You're starting to come out of grief or disappointment. Slowly, but you're moving. That's already something.",
  },
  cups6: {
    ru: "День ностальгии и тёплых воспоминаний. Может встретить кого-то из прошлого или вспомнить что-то хорошее. Позволь себе это — воспоминания могут принести подсказку.",
    ruRev: "Ты застрял в прошлом — идеализируешь то что было или не можешь отпустить. Прошлое хорошо как фундамент, плохо как место жительства.",
    en: "Day of nostalgia and warm memories. You might run into someone from the past or recall something good. Let yourself — memories can bring a clue.",
    enRev: "You're stuck in the past — idealizing what was or unable to let go. The past is good as a foundation, bad as a place to live.",
  },
  cups7: {
    ru: "Много вариантов, много желаний — но что из этого реально? Сегодня важно отделить фантазии от реальных возможностей и выбрать одно направление.",
    ruRev: "Туман рассеивается — ты начинаешь видеть что действительно важно, а что было иллюзией. Хороший момент чтобы принять взвешенное решение.",
    en: "Lots of options, lots of desires — but what's actually real? Today it's important to separate fantasies from real possibilities and pick one direction.",
    enRev: "The fog is clearing — you're starting to see what actually matters and what was an illusion. Good moment to make a grounded decision.",
  },
  cups8: {
    ru: "Что-то перестало приносить радость и ты это чувствуешь. Иногда уйти — это не слабость, а честность с собой. Подумай что ты держишь из привычки а не из любви.",
    ruRev: "Ты уходишь или думаешь уйти — но что-то держит. Страх, привязанность, неизвестность. Стоит разобраться что именно прежде чем принимать решение.",
    en: "Something has stopped bringing you joy and you feel it. Sometimes leaving isn't weakness — it's honesty with yourself. Think about what you're holding onto out of habit rather than love.",
    enRev: "You're leaving or thinking about leaving — but something is holding you back. Fear, attachment, uncertainty. Worth figuring out what exactly before making a decision.",
  },
  cups9: {
    ru: "Карта желания — и хорошая новость: сегодня есть шанс что желаемое сбудется или сделает шаг к тебе. Позволь себе хотеть и не стесняйся этого.",
    ruRev: "Получил что хотел — но не так радостно как ожидал? Или желание оказалось не своим. Стоит честно ответить себе — чего ты на самом деле хочешь.",
    en: "The wish card — and good news: today there's a chance what you want will come true or take a step toward you. Let yourself want things and don't be ashamed of it.",
    enRev: "Got what you wanted — but it's not as satisfying as expected? Or the desire turned out not to be yours. Worth honestly asking yourself — what do you actually want.",
  },
  cups10: {
    ru: "День тепла, гармонии и ощущения что всё на своём месте. Побудь в этом, не ищи проблем там где их нет. Иногда просто хорошо — это достаточно.",
    ruRev: "Внешне всё хорошо, но внутри что-то не так. Возможно дома или в близких отношениях есть напряжение которое пора признать и обсудить.",
    en: "Day of warmth, harmony and the feeling that everything is in its place. Stay in this, don't look for problems where there aren't any. Sometimes just good is enough.",
    enRev: "Things look fine on the outside but something feels off inside. There might be tension at home or in close relationships that needs to be acknowledged and talked about.",
  },
  cups11: {
    ru: "День для творчества, мечтания и эмоциональной открытости. Позволь себе немного наивности и чуда — иногда самые нелогичные идеи оказываются лучшими.",
    ruRev: "Эмоции немного зашкаливают или ты слишком чувствителен к мелочам. Дай себе время прийти в баланс прежде чем реагировать.",
    en: "Day for creativity, dreaming and emotional openness. Allow yourself a little naivety and wonder — sometimes the most illogical ideas are the best ones.",
    enRev: "Emotions are running a bit high or you're overly sensitive to small things. Give yourself time to find balance before reacting.",
  },
  cups12: {
    ru: "День романтики и следования сердцу. Если есть что-то что давно хотел сказать или сделать из любви — сегодня хороший момент.",
    ruRev: "Эмоции управляют тобой больше чем следует. Или ты идеализируешь ситуацию и видишь то что хочешь, а не то что есть. Добавь немного трезвости.",
    en: "Day of romance and following your heart. If there's something you've long wanted to say or do out of love — today is a good moment.",
    enRev: "Emotions are driving you more than they should. Or you're idealizing the situation and seeing what you want rather than what's there. Add a dose of realism.",
  },
  cups13: {
    ru: "День для заботы — о себе и других. Ты сегодня особенно чуткий и это твоя сила. Хороший день для глубоких разговоров и поддержки близких.",
    ruRev: "Ты либо тонешь в чужих эмоциях забывая о себе, либо наоборот — закрылся от всех. Найди баланс между заботой о других и заботой о себе.",
    en: "Day for care — for yourself and others. You're especially perceptive today and that's your strength. Good day for deep conversations and supporting those close to you.",
    enRev: "You're either drowning in others' emotions and forgetting yourself, or you've closed off from everyone. Find the balance between caring for others and caring for yourself.",
  },
  cups14: {
    ru: "День эмоциональной зрелости. Ты можешь сегодня быть опорой — для себя или других. Чувствовать и при этом не терять голову — это большая сила.",
    ruRev: "Эмоции выходят из-под контроля или ты подавляешь их слишком жёстко. Ни то ни другое не работает долго. Найди способ проживать чувства без разрушения.",
    en: "Day of emotional maturity. You can be a pillar today — for yourself or others. Feeling deeply while keeping your head — that's real strength.",
    enRev: "Emotions are getting out of control, or you're suppressing them too hard. Neither works long term. Find a way to experience feelings without destruction.",
  },
  swords1: {
    ru: "День ясности и честности. Отличный момент чтобы наконец назвать вещи своими именами — в разговоре с собой или с другими. Правда режет, но освобождает.",
    ruRev: "Есть что-то что ты не хочешь видеть или признавать. Избегание только усугубляет. Попробуй посмотреть на ситуацию прямо, даже если неприятно.",
    en: "Day of clarity and honesty. Great moment to finally call things what they are — in a conversation with yourself or others. Truth cuts, but it frees.",
    enRev: "There's something you don't want to see or acknowledge. Avoidance only makes it worse. Try looking at the situation directly, even if it's uncomfortable.",
  },
  swords2: {
    ru: "Ты избегаешь решения — закрылся и не хочешь смотреть. Понятно, но не бесконечно. Когда будешь готов — информация уже есть, надо просто открыть глаза.",
    ruRev: "Завеса начинает спадать — ты видишь ситуацию яснее. Теперь у тебя достаточно информации чтобы принять решение.",
    en: "You're avoiding a decision — closed off and not wanting to look. Understandable, but it can't go on forever. When you're ready — the information is already there, you just need to open your eyes.",
    enRev: "The veil is starting to lift — you're seeing the situation more clearly. Now you have enough information to make a decision.",
  },
  swords3: {
    ru: "Что-то болит. Разрешается разочарование, обида, горе. Не пытайся заглушить — дай себе прожить это. Боль которую проживают, проходит. Та что подавляют — остаётся.",
    ruRev: "Боль начинает отступать. Медленно, но заживает. Ты уже немного дальше от самого острого момента.",
    en: "Something hurts. Disappointment, hurt feelings, grief are processing. Don't try to numb it — let yourself go through it. Pain that's felt passes. Pain that's suppressed stays.",
    enRev: "The pain is starting to ease. Slowly, but it's healing. You're already a little further from the sharpest moment.",
  },
  swords4: {
    ru: "Тело и голова просят отдыха. Не геройствуй — сделай сегодня меньше но восстановись. Завтра будешь эффективнее чем если будешь гнать себя сегодня.",
    ruRev: "Хватит отдыхать — пора возвращаться. Пауза затянулась и теперь мешает больше чем помогает. Время снова в строй.",
    en: "Your body and mind are asking for rest. Don't push through — do less today and recover. Tomorrow you'll be more effective than if you drive yourself into the ground today.",
    enRev: "Enough rest — time to get back. The pause has gone on too long and now it's holding you back more than helping. Time to get back in action.",
  },
  swords5: {
    ru: "Не всякую битву стоит выигрывать. Иногда победа обходится дороже чем поражение — отношениями, репутацией, внутренним миром. Спроси себя: оно того стоит?",
    ruRev: "Конфликт стихает или ты решаешь не продолжать бой. Мудрое решение. Иногда отступить — это не слабость, а зрелость.",
    en: "Not every battle is worth winning. Sometimes victory costs more than defeat — in relationships, reputation, inner peace. Ask yourself: is it worth it?",
    enRev: "A conflict is settling or you're choosing not to continue the fight. Wise decision. Sometimes stepping back isn't weakness — it's maturity.",
  },
  swords6: {
    ru: "Ты двигаешься от чего-то тяжёлого к чему-то более спокойному. Это не быстро и не легко, но движение есть. Продолжай.",
    ruRev: "Переход затягивается или ты сопротивляешься переменам. Что именно держит тебя в той точке откуда давно пора уйти?",
    en: "You're moving away from something heavy toward something calmer. It's not fast or easy, but movement is happening. Keep going.",
    enRev: "The transition is dragging or you're resisting the change. What exactly is keeping you at the point you should have left a long time ago?",
  },
  swords7: {
    ru: "Будь внимателен — что-то может быть не тем чем кажется. Или ты сам пытаешься обойти ситуацию по-тихому. В любом случае честность сейчас надёжнее хитрости.",
    ruRev: "Что-то скрытое выходит на поверхность. Либо чья-то игра раскрывается, либо ты сам решаешь быть честным. Второе — лучший вариант.",
    en: "Stay alert — something might not be what it seems. Or you yourself are trying to handle a situation quietly. Either way, honesty is more reliable than cleverness right now.",
    enRev: "Something hidden is coming to the surface. Either someone's game is being revealed, or you're choosing to be honest yourself. The second is the better option.",
  },
  swords8: {
    ru: "Ты чувствуешь себя в ловушке — но посмотри внимательнее. Большинство ограничений сейчас у тебя в голове. Один маленький шаг в сторону покажет что выход есть.",
    ruRev: "Ты начинаешь видеть выход. Повязка спадает. Ещё немного и ты поймёшь что свободен — был свободен всё это время.",
    en: "You feel trapped — but look more carefully. Most of the limitations right now are in your head. One small step to the side will show you that a way out exists.",
    enRev: "You're starting to see the exit. The blindfold is falling. A little more and you'll realize you're free — you were free this whole time.",
  },
  swords9: {
    ru: "Тревога и тёмные мысли крутятся в голове — особенно ночью. Напомни себе: большинство из того чего боишься не случится. А то что случится — переживёшь.",
    ruRev: "Тревога начинает отступать. Ты либо нашёл способ справляться, либо ситуация начала проясняться. Продолжай в том же духе.",
    en: "Anxiety and dark thoughts are swirling — especially at night. Remind yourself: most of what you fear won't happen. And what does happen — you'll get through.",
    enRev: "The anxiety is starting to ease. Either you've found a way to cope, or the situation is beginning to clarify. Keep it up.",
  },
  swords10: {
    ru: "Что-то закончилось — и это было болезненно. Но дно это и есть точка откуда начинается подъём. Хуже уже не будет. Только вперёд.",
    ruRev: "Ты начинаешь подниматься после тяжёлого периода. Медленно, с трудом — но подъём есть. Это уже победа.",
    en: "Something has ended — and it was painful. But the bottom is exactly where the climb back up begins. It won't get worse. Only forward.",
    enRev: "You're starting to rise after a hard period. Slowly, with difficulty — but you are rising. That's already a victory.",
  },
  swords11: {
    ru: "День для острого ума и любопытства. Задавай вопросы, исследуй, ищи информацию. Только не режь правдой без необходимости — не все готовы к твоей прямолинейности.",
    ruRev: "Слова могут навредить сегодня — свои или чужие. Думай прежде чем говорить и не верь всему что услышишь.",
    en: "Day for a sharp mind and curiosity. Ask questions, explore, seek information. Just don't cut with truth unnecessarily — not everyone is ready for your directness.",
    enRev: "Words can cause harm today — yours or someone else's. Think before you speak and don't believe everything you hear.",
  },
  swords12: {
    ru: "Энергия и скорость есть — используй их для дела. Хороший день чтобы разрубить узел который давно тянется. Только не сноси всё подряд в порыве.",
    ruRev: "Ты несёшься вперёд не думая о последствиях. Или наоборот — застрял и не можешь сдвинуться. В обоих случаях нужна пауза для осмысления.",
    en: "Energy and speed are there — use them for something real. Good day to cut through a knot that's been dragging on. Just don't bulldoze everything in the rush.",
    enRev: "You're charging forward without thinking about consequences. Or the opposite — stuck and can't move. Either way, a pause to think things through is needed.",
  },
  swords13: {
    ru: "День для ясных решений без эмоционального тумана. Ты можешь видеть ситуацию чётко и называть вещи своими именами. Это ценно — используй.",
    ruRev: "Ты слишком холоден или резок — режешь там где можно было мягче. Ясность мышления не обязана быть жестокостью.",
    en: "Day for clear decisions without emotional fog. You can see the situation clearly and call things what they are. That's valuable — use it.",
    enRev: "You're being too cold or sharp — cutting where you could have been gentler. Clear thinking doesn't have to be cruelty.",
  },
  swords14: {
    ru: "День для стратегического мышления и взвешенных решений. Ты можешь видеть всю картину — используй это чтобы принять решение которое выдержит проверку временем.",
    ruRev: "Власть или знание используются не так — для манипуляции, давления, или наоборот ты не берёшь ответственность когда должен. Пора с этим разобраться.",
    en: "Day for strategic thinking and considered decisions. You can see the full picture — use it to make a decision that will stand the test of time.",
    enRev: "Power or knowledge is being misused — for manipulation, pressure, or you're not taking responsibility when you should. Time to sort this out.",
  },
  pentacles1: {
    ru: "Новое начало в материальной сфере — работа, деньги, проект, здоровье. Хороший день чтобы заложить фундамент. Посеянное сегодня даст результат.",
    ruRev: "Возможность есть, но ты её не видишь или не берёшь. Возможно слишком много сомнений. Иногда надо просто взять то что дают.",
    en: "A new beginning in the material realm — work, money, a project, health. Good day to lay a foundation. What's planted today will bear fruit.",
    enRev: "There's an opportunity but you're not seeing it or taking it. Maybe too many doubts. Sometimes you just have to take what's being offered.",
  },
  pentacles2: {
    ru: "Жонглируешь несколькими делами одновременно. Пока справляешься — но не переусердствуй. Расставь приоритеты чтобы не уронить то что важно.",
    ruRev: "Слишком много всего сразу и ты начинаешь терять баланс. Что-то нужно убрать из списка. Не всё одинаково важно.",
    en: "You're juggling several things at once. Managing for now — but don't overdo it. Set priorities so you don't drop what matters.",
    enRev: "Too much at once and you're starting to lose balance. Something needs to come off the list. Not everything is equally important.",
  },
  pentacles3: {
    ru: "День для совместной работы и мастерства. Хорошее время чтобы поработать в команде, получить обратную связь или показать свою экспертизу.",
    ruRev: "Что-то не так в командной работе — непонимание, разные цели, кто-то халтурит. Стоит разобраться до того как это стало серьёзной проблемой.",
    en: "Day for teamwork and craftsmanship. Good time to work with others, get feedback, or show your expertise.",
    enRev: "Something's off in the teamwork — misunderstanding, different goals, someone slacking. Worth sorting out before it becomes a serious problem.",
  },
  pentacles4: {
    ru: "Ты держишься за то что имеешь — и это понятно. Но посмотри: не мешает ли страх потерять двигаться вперёд? Стабильность хороша, жадность — нет.",
    ruRev: "Ты начинаешь отпускать контроль над ресурсами — деньгами, временем, вещами. Это освобождает. Доверие что всего хватит — это тоже сила.",
    en: "You're holding onto what you have — and that's understandable. But check: is fear of losing blocking you from moving forward? Stability is good, hoarding is not.",
    enRev: "You're starting to let go of control over resources — money, time, things. That's freeing. Trusting that there's enough — that's also a kind of strength.",
  },
  pentacles5: {
    ru: "Трудный период — финансово, физически или ощущение что остался один. Но помощь ближе чем кажется. Позволь себе её принять.",
    ruRev: "Трудный период начинает заканчиваться. Финансовая или физическая ситуация медленно улучшается. Держись — поворот уже виден.",
    en: "A hard period — financially, physically, or feeling like you're on your own. But help is closer than it seems. Let yourself accept it.",
    enRev: "The hard period is starting to end. A financial or physical situation is slowly improving. Hold on — the turning point is already visible.",
  },
  pentacles6: {
    ru: "День для щедрости и баланса в обмене. Ты либо даёшь либо получаешь — в обоих случаях делай это с достоинством, без долга и без жертвы.",
    ruRev: "Дисбаланс в отдаче и получении. Ты либо даёшь слишком много и не получаешь ничего взамен, либо берёшь не отдавая. Пора восстановить баланс.",
    en: "Day for generosity and balance in exchange. You're either giving or receiving — in both cases do it with dignity, without obligation and without sacrifice.",
    enRev: "Imbalance in giving and receiving. You're either giving too much and getting nothing back, or taking without giving. Time to restore balance.",
  },
  pentacles7: {
    ru: "Ты вложил много — и теперь ждёшь результата. Сегодня хороший день чтобы оценить прогресс честно. Всё ли идёт туда куда ты хочешь?",
    ruRev: "Вкладываешь много, а отдачи мало. Стоит пересмотреть куда уходит энергия — возможно что-то давно пора бросить и вложиться во что-то более перспективное.",
    en: "You've put in a lot — and now you're waiting for results. Today is a good day to honestly assess the progress. Is everything going where you want it to?",
    enRev: "You're investing a lot but getting little return. Worth reviewing where your energy is going — maybe something should have been dropped a long time ago in favor of something more promising.",
  },
  pentacles8: {
    ru: "День для работы и развития навыков. Делай то что делаешь — хорошо и внимательно. Мастерство растёт не от вдохновения а от повторения.",
    ruRev: "Ты либо застрял в рутине без роста, либо берёшься за всё но ничего не доводишь до мастерства. Выбери одно и углубись.",
    en: "Day for work and skill development. Do what you do — well and carefully. Mastery grows not from inspiration but from repetition.",
    enRev: "You're either stuck in routine without growth, or trying everything but not mastering anything. Pick one thing and go deep.",
  },
  pentacles9: {
    ru: "День для удовольствия от того что ты создал. Позволь себе насладиться результатами своего труда — без извинений и без «надо ещё больше». Ты заработал это.",
    ruRev: "Внешне всё хорошо, но внутри ощущение пустоты или зависимости от чего-то. Стоит разобраться что на самом деле даёт тебе ощущение безопасности.",
    en: "Day to enjoy what you've built. Allow yourself to savor the results of your work — without apology and without 'I need to do more'. You've earned this.",
    enRev: "Things look good on the outside but there's an inner emptiness or dependence on something. Worth figuring out what actually gives you a sense of security.",
  },
  pentacles10: {
    ru: "День стабильности и наследия. Подумай о том что строишь — не только для себя но и для тех кто рядом. Долгосрочное мышление сегодня в приоритете.",
    ruRev: "Что-то нарушает стабильность в доме или семье. Или ты ставишь деньги выше всего остального. Посмотри что действительно важно в долгую.",
    en: "Day of stability and legacy. Think about what you're building — not just for yourself but for those around you. Long-term thinking is the priority today.",
    enRev: "Something is disrupting stability at home or in the family. Or you're putting money above everything else. Look at what actually matters in the long run.",
  },
  pentacles11: {
    ru: "День для обучения и новых практических навыков. Хороший момент чтобы начать изучать то что давно хотел — не теорию а что-то конкретное и применимое.",
    ruRev: "Много планов, мало действий. Или ты учишься но не применяешь. Знания без практики — просто информация. Сделай хотя бы один реальный шаг.",
    en: "Day for learning and new practical skills. Good moment to start studying something you've long wanted — not theory but something concrete and applicable.",
    enRev: "Lots of plans, little action. Or you're learning but not applying. Knowledge without practice is just information. Take at least one real step.",
  },
  pentacles12: {
    ru: "День для надёжной, методичной работы. Не самый быстрый темп, но зато качественный результат. Сделай меньше но хорошо — это лучше чем много но кое-как.",
    ruRev: "Ты застрял в рутине или наоборот — слишком упрям чтобы поменять подход который не работает. Иногда надо просто попробовать по-другому.",
    en: "Day for reliable, methodical work. Not the fastest pace, but a quality result. Do less but do it well — that's better than a lot done poorly.",
    enRev: "You're stuck in routine or, on the contrary, too stubborn to change an approach that isn't working. Sometimes you just have to try a different way.",
  },
  pentacles13: {
    ru: "День для заботы о практическом — доме, теле, финансах, близких. Ты умеешь создавать уют и стабильность — сегодня это особенно ценно.",
    ruRev: "Ты либо слишком поглощён бытом в ущерб себе, либо пренебрегаешь практическими делами. Найди баланс между заботой о других и о себе.",
    en: "Day for taking care of the practical — home, body, finances, loved ones. You know how to create comfort and stability — today that's especially valuable.",
    enRev: "You're either too absorbed in day-to-day matters at your own expense, or neglecting the practical things. Find balance between caring for others and for yourself.",
  },
  pentacles14: {
    ru: "День для зрелых решений в финансах и делах. Ты знаешь что делаешь — доверяй этому знанию. Хороший момент для крупных договорённостей или инвестиций.",
    ruRev: "Деньги или власть используются не лучшим образом — скупость, контроль, или наоборот расточительство. Посмотри на своё отношение к ресурсам честно.",
    en: "Day for mature decisions in finances and business. You know what you're doing — trust that knowledge. Good moment for major agreements or investments.",
    enRev: "Money or power is being used poorly — stinginess, control, or on the contrary, wastefulness. Look honestly at your relationship with resources.",
  },
};
